### ISSUE TITLE
upload directly from a haxball bot

### ISSUE THREAD

**Issue by tanercanbilgin** [saviola777/haxball-hbr2-uploader#2]
hey! is there a way to upload haxball recordings from bot directly to your website and get the link? thanks

**Comment by saviola777** [comment]
Hi, if you look at the upload.php script, it should be possible to call this directly from your bot, and you should get a JSON response with the replay URL. It might not work due to CORS issues though. If that's the case, you may have to host your own instance on your VPS.

I don't want to officially support or encourage this, because it will flood my VPS which has limited storage – my uploader page was originally intended as a backup / niche solution for the FM community. But since it is open source, everyone is free to host their own uploader!

**Comment by tanercanbilgin** [comment]
thank you so much, i wanted to create my own system but i didnt want to buy another vds for it. i saw your project and wanted to use it but now i understood its purpose.
